/* English text. Each line is "key": "words shown on the site". */
window.I18N = window.I18N || {};
window.I18N.en = {
  "tb.addr": "4490 Aurora Rd, Melbourne, FL 32934",
  "tb.hours": "Mon-Sat 10:30 AM - 2:00 PM  |  Sun 9:00 AM - 12:00 PM",
  "brand.name": "Wat Punyawanaram",
  "brand.tag": "Thai Buddhist Temple",
  "nav.home": "Home",
  "nav.about": "About Us",
  "nav.events": "Events",
  "nav.gallery": "Gallery",
  "nav.teaching": "Dharma Teaching",
  "nav.shop": "Gift & Garden Shop",
  "nav.project": "Featured Project",
  "nav.contact": "Contact",
  "nav.donate": "Donate",
  "foot.about": "A Thai Buddhist temple in Melbourne, Florida. Everyone is welcome.",
  "foot.visit": "Visit Us",
  "foot.links": "Quick Links",
  "foot.note": "This is a sample website for demonstration only. All text and pictures are placeholders.",
  "demo.title": "For Demo Only",
  "demo.body": "This is a sample website. Nothing was purchased, donated or sent.",
  "demo.close": "Close",
  "title.about": "About Us | Wat Punyawanaram",
  "a.title": "About Us",
  "a.sub": "Our story, our mission and our monks",
  "a.h.eyebrow": "OUR STORY",
  "a.h.title": "A Thai temple in the heart of Brevard County",
  "a.h.p1": "Wat Punyawanaram of Melbourne was incorporated as a nonprofit in 1991. For over three decades it has been a home for the Thai community and a welcoming place for anyone curious about Buddhism.",
  "a.h.p2": "Our mission is to preserve Thai Buddhist traditions, offer teachings and meditation, and share Thai culture with our neighbors. (Sample text. The temple will provide the final wording.)",
  "a.v.eyebrow": "WHAT WE VALUE",
  "a.v.title": "Our values",
  "a.v1.t": "Compassion",
  "a.v1.p": "We care for one another and for every visitor who walks through our doors.",
  "a.v2.t": "Mindfulness",
  "a.v2.p": "We practice paying attention to the present moment, one breath at a time.",
  "a.v3.t": "Community",
  "a.v3.p": "We share food, festivals and friendship across cultures.",
  "a.m.eyebrow": "OUR MONKS",
  "a.m.p": "Phrakru Charn gives regular sermons in English and welcomes questions from newcomers. (Sample bio. The temple will provide the real one.)",
  "a.m.btn": "See Upcoming Talks",
  "title.contact": "Contact & Visit | Wat Punyawanaram",
  "c.title": "Contact & Visit",
  "c.sub": "We would love to meet you",
  "c.h": "Visit the temple",
  "c.addr": "Address",
  "c.phone": "Phone",
  "c.hours": "Hours",
  "foot.hours1": "Mon-Sat: 10:30 AM - 2:00 PM",
  "foot.hours2": "Sunday: 9:00 AM - 12:00 PM",
  "c.fb": "Facebook",
  "c.v.title": "First time visiting?",
  "c.v1": "Dress modestly. Cover your shoulders and knees.",
  "c.v2": "Remove your shoes before entering the hall.",
  "c.v3": "Monks do not touch or hand things to women. Ask if you are unsure.",
  "c.v4": "Questions are welcome. Everyone here was a beginner once.",
  "c.f.title": "Send us a message",
  "c.f.name": "Your name",
  "c.f.email": "Email",
  "c.f.msg": "Message",
  "c.f.send": "Send Message",
  "title.donate": "Donate | Wat Punyawanaram",
  "d.title": "Donate",
  "d.sub": "Thank you for supporting the temple",
  "d.h": "Choose a gift amount",
  "d.p": "Your gift supports our monks, our building and our community programs. (Sample page. No payments are taken.)",
  "d.other": "Other Amount",
  "d.w.title": "Other ways to give",
  "d.w1": "In person: visit us during temple hours and give to the temple directly.",
  "d.w2": "By mail: Wat Punyawanaram, 4490 Aurora Rd, Melbourne, FL 32934.",
  "title.events": "Events | Wat Punyawanaram",
  "e.title": "Events",
  "e.sub": "Join us for food, teachings and celebrations",
  "e.note": "Sample events. Dates and times will be updated before the site goes live.",
  "ev1.day": "SUN",
  "ev1.mon": "Weekly",
  "ev1.t": "Sunday Thai Food Market",
  "ev1.time": "Every Sunday, 9:00 AM until about noon",
  "ev1.p": "Thai dishes, a Sunday buffet and market goodies from friendly vendors. Cash only.",
  "ev2.day": "18",
  "ev2.mon": "Oct",
  "ev2.t": "A Sermon in English: The Power of Right Effort",
  "ev2.time": "Sunday, Oct 18, 12:30 PM (sample date)",
  "ev2.p": "Phrakru Charn gives a talk in English. Sponsored by Peace Talkers Toastmasters Club and English Wednesday Club.",
  "ev3.day": "WED",
  "ev3.mon": "Weekly",
  "ev3.t": "Beginner Meditation Class",
  "ev3.time": "Wednesdays, 6:00 PM (sample time)",
  "ev3.p": "Learn simple sitting and walking meditation. No experience needed.",
  "ev4.day": "1",
  "ev4.mon": "Nov",
  "ev4.t": "Kathina Robe Offering Ceremony",
  "ev4.time": "Sunday, Nov 1 (sample date)",
  "ev4.p": "Our yearly ceremony to offer new robes and supplies to the monks.",
  "ev5.day": "NOV",
  "ev5.mon": "Late",
  "ev5.t": "Loy Krathong Festival",
  "ev5.time": "Late November (sample date)",
  "ev5.p": "Floating lanterns, Thai music, dance and food for the whole family.",
  "title.gallery": "Gallery | Wat Punyawanaram",
  "g.title": "Gallery",
  "g.sub": "Moments from temple life",
  "g.note": "Sample pictures. Real temple photos will replace these.",
  "title.home": "Wat Punyawanaram | Thai Buddhist Temple in Melbourne, Florida",
  "h.hero.title": "Welcome to Wat Punyawanaram",
  "h.hero.sub": "A Thai Buddhist temple in Melbourne, Florida. Come share a meal, learn to meditate and meet your neighbors. Everyone is welcome.",
  "h.hero.b1": "Plan Your Visit",
  "h.hero.b2": "Sunday Food Market",
  "h.new.eyebrow": "NEW HERE?",
  "h.new.title": "Three easy ways to get to know us",
  "h.c1.t": "Join us on Sunday",
  "h.c1.p": "Our Sunday gathering is the best way to meet the temple community. Come for the food market and stay for the English sermon.",
  "h.c2.t": "Learn to meditate",
  "h.c2.p": "No experience needed. Our monks teach simple meditation in plain English.",
  "h.c3.t": "Be part of the family",
  "h.c3.p": "Volunteer, celebrate Thai festivals and make lasting friendships.",
  "m.badge": "EVERY SUNDAY",
  "m.title": "Sunday Thai Food Market",
  "m.p": "A warm community gathering with authentic Thai dishes, a Sunday buffet and market goodies from friendly vendors. It is the easiest way to experience Thai culture, and everyone is welcome.",
  "m.time": "Sundays, 9:00 AM until about noon",
  "m.t1": "Come early. The food is popular and sells out quickly.",
  "m.t2": "Cash only. Vendors do not accept credit cards.",
  "m.t3": "Bring a reusable bag or containers to take food home.",
  "m.btn": "Get Directions",
  "h.about.eyebrow": "ABOUT US",
  "h.about.title": "A place of peace in Melbourne",
  "h.about.p": "Our temple has been part of the Melbourne community since 1991. We welcome neighbors of every background to meditate, learn and celebrate together.",
  "h.about.btn": "Learn More",
  "h.don.title": "Your generosity keeps the temple open to everyone",
  "h.don.p": "Gifts of every size support our monks, our building and our community programs.",
  "h.don.btn": "Donate Now",
  "h.proj.eyebrow": "FEATURED PROJECT",
  "h.proj.title": "Meditation Pavilion (sample project)",
  "h.proj.p": "We are raising funds for a quiet, open-air pavilion where visitors can meditate and reflect. Every gift, big or small, helps build it.",
  "h.proj.btn": "See the Project",
  "h.ev.eyebrow": "EVENTS",
  "h.ev.title": "Upcoming Events",
  "h.ev.all": "See All Events",
  "title.project": "Featured Project | Wat Punyawanaram",
  "p.title": "Featured Project",
  "p.sub": "Help us build something lasting",
  "p.eyebrow": "SAMPLE PROJECT",
  "p.h": "The Meditation Pavilion",
  "p.p1": "A quiet, open-air pavilion where visitors can sit, walk and reflect, surrounded by the temple gardens. (Sample project. The temple will describe its real project here.)",
  "p.goal": "$62,000 raised of a $100,000 goal (sample numbers)",
  "p.btn": "Give to This Project",
  "title.shop": "Gift & Garden Shop | Wat Punyawanaram",
  "s.title": "Gift & Garden Shop",
  "s.sub": "Gifts, plants and handmade art that support the temple",
  "s.n1": "Are you an artist?",
  "s.n2": "Local artists can list their work here and share the proceeds with the temple.",
  "s.n3": "Contact us to become a seller.",
  "s.i1": "Lotus Candle",
  "s.buy": "Buy Now",
  "s.i2": "Small Buddha Statue",
  "s.i3": "Orchid Plant",
  "s.i4": "Hand-Painted Lotus Art",
  "s.i5": "Incense Gift Set",
  "s.i6": "Prayer Beads",
  "title.teaching": "Dharma Teaching | Wat Punyawanaram",
  "t.title": "Dharma Teaching",
  "t.sub": "Meditation and Buddhist teachings for beginners and beyond",
  "t.m.eyebrow": "MEDITATION",
  "t.m.title": "Meditation for beginners",
  "t.m.p": "Never meditated before? Perfect. Our monks teach sitting and walking meditation step by step, in English. Classes are free and open to everyone. (Sample schedule.)",
  "t.m.btn": "See the Schedule",
  "t.b.eyebrow": "BUDDHIST BASICS",
  "t.b.title": "Ideas to start with",
  "t.b1.t": "The Four Noble Truths",
  "t.b1.p": "Life includes suffering, suffering has causes, it can end, and there is a path to its end.",
  "t.b2.t": "The Eightfold Path",
  "t.b2.p": "Right view, thought, speech, action, livelihood, effort, mindfulness and concentration.",
  "t.b3.t": "The Five Precepts",
  "t.b3.p": "Simple promises: do no harm, take only what is given, speak truthfully, act with care and keep a clear mind.",
};
